version: '3.8'
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - carat-net

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_BASE=http://backend:8080
    depends_on:
      - backend
    networks:
      - carat-net

networks:
  carat-net:
    driver: bridge
